### PR TITLE
Fix: some Android webviews and Firefox for Android do not properly handle intent URLs

### LINKED ISSUE #39: Integrate browser fallback functionality to prevent the IRMA app failing to open
When trying to load attributes e.g. with DigiD with a alternate default browser set, you could end up with a redirect to the app store webpage. This is because e.g. Firefox does not open app-links by default (privacy measure), which triggers the redirect. This could be solved within the app (WebView), or within the Gemeente Nijmegen-flow.

Version app: 6.0.11
Alternate default browser: Firefox Mobile
Android 10

Steps:
- Open IRMA app
- Voeg meer gegevens toe
- Klik woonadres / persoonsgegevens
- Voeg toe
- Inloggen met DigiD
- You end up with the webview of the irma app, app store webpage.

### PR DESCRIPTION
**Pull request by ivard**
If you have issues running the examples for testing, please say so. I can update the AngryGames on staging to make it easier for you to test.

Fixes #39

### CODE REVIEW

**Comment by ivard** [comment]
I did some rebasing such that the replacement of intent URLs for scheme URLs is in a separate commit, in case we want to change it.

File: plugins/irma-client/server-state.js [hunk 1]
```diff
@@ -113,13 +123,13 @@ module.exports = class ServerState {
...
-      .then(r => {
-        if ( r.status != 200 )
-          throw(`Error in fetch: endpoint returned status other than 200 OK. Status: ${r.status} ${r.statusText}`);
-        return r;
+      // On Firefox for Android pending fetch request are actively aborted when navigating.
+      // So in case of an error, we do a second attempt to assure the error is permanent.
+      this._pollOnce()
+      .catch(() => {
+        if (this._options.debugging) console.log('Polling attempt failed; doing a second attempt to confirm error');
+        return this._pollOnce();
```
Comment (sietseringers) [inline plugins/irma-client/server-state.js:131]: Is this necessary for the rest of the MR to work, and if so, how?

Comment (ivard) [reply plugins/irma-client/server-state.js:131]: Yes and no. Strictly it is not part of the fix indeed. However, when I fixed the `intent://` bug started testing on Firefox, I saw that rather often it randomly failed on Firefox. It failed that often that I thought that I had to fix that too. Otherwise, the previous bug fix wouldn't be very useful.

**Review by sietseringers — APPROVED** [review]
